In [1]:
#3.2 多維張量
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[0] = 3.0
a

[3.0, 2.0, 1.0]

In [4]:
import torch #匯入 torch 模組
a = torch.ones(3) #創建一個 3 維的 1 軸張量，其元素皆為 1 
a

tensor([1., 1., 1.])

In [5]:
a[1] #印出索引為 1 的元素

tensor(1.)

In [6]:
float(a[1]) #將 a[1] 轉換為浮點數後再輸出

1.0

In [7]:
a[2] = 2.0 #修改索引為 2 的元素
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6) #利用 zeros() 來創建初始元素值皆為 0 的 1 軸張量
points[0] = 4.0 #點 A 的 x 座標
points[1] = 1.0 #點 A 的 y 座標
points[2] = 5.0 #點 B 的 x 座標
points[3] = 3.0 #點 B 的 y 座標
points[4] = 2.0 #點 C 的 x 座標
points[5] = 1.0 #點 C 的 y 座標
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0]) #存有座標值的串列
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
#點 A 的 x 座標, 點 A 的 x 座標
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[0] #用索引 0 來提取點 A 的座標值

tensor([4., 1.])

In [12]:
points.shape #shape 會回傳張量在每個軸的維度
# 輸出: torch.Size([3, 2]) 表示 points 為 2 軸張量，第 0 軸有 3 維，第 1 軸有 2 維。

torch.Size([3, 2])

In [13]:
points = torch.zeros(3, 2) #創建一個元素值全為 0 的張量，並指定期 shape 為(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]) #先創建一個 2 軸張量
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1] #取出第 0 列，第 1 行的元素

tensor(1.)

In [16]:
#3.3 利用索引值操作張量
some_list = list(range(6)) #產生一個 0 到 5 的數字串列
some_list[:] #提取串列中所有元素

[0, 1, 2, 3, 4, 5]

In [17]:
some_list[0:4] #提取第 0 個到第 3 個元素

[0, 1, 2, 3]

In [18]:
some_list[1:] #提取第 1 個元素到最後一個元素

[1, 2, 3, 4, 5]

In [19]:
some_list[:4] #提取第 0 個元素到第 3 個元素

[0, 1, 2, 3]

In [20]:
some_list[:-1] #提取第 0 個到倒數第二個元素

[0, 1, 2, 3, 4]

In [21]:
some_list[1:4:2] #從第 1 個元素到第 3 個元素，每次間隔 2 個元素

[1, 3]

In [22]:
points #利用前面的 points 張量

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [23]:
points[1:, :] #提取第 1 列起所有元素

tensor([[5., 3.],
        [2., 1.]])

In [24]:
points[1:, 0] #提取第 1 列起，位於第 0 行的元素

tensor([5., 2.])

In [25]:
#為張量命名

#將第 0 軸命名為channels，此張量只有一個軸，shape 為 (3,)
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

d:\anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  after removing the cwd from sys.path.


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [26]:
img_t = torch.randn(3, 5, 5) #創建一個 3 軸張量
batch_t = torch.randn(2, 3, 5, 5) #創建一個 4 軸張量

img_named = img_t.refine_names(..., 'channels', 'rows', 'columns') #針對張量最後三個軸分別命名，'...'表示要略過該軸
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')

print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names) #未命名的軸以 none 表示

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [27]:
#weights_named 為 1 軸張量，只有 channels 軸
weights_aligned = weights_named.align_as(img_named) #align_as 會將前者對齊後者的軸順序並自動擴張
weights_aligned.shape, weights_aligned.names #變成 1 個 3 軸張量，自動添加 rows 和 columns 軸

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [28]:
(img_named * weights_aligned)

tensor([[[ 1.4493e-01, -1.0694e-02, -9.6964e-02,  7.9767e-02, -1.4366e-01],
         [-1.3180e-01, -1.0499e-01,  4.5727e-01,  2.5240e-01, -1.5206e-02],
         [ 2.0946e-02, -9.2050e-02, -4.9546e-02,  2.9886e-02,  9.6666e-02],
         [ 2.4582e-01, -1.1718e-01, -1.2161e-01,  1.9325e-01, -6.7592e-02],
         [ 3.9028e-02,  1.1417e-01,  1.4450e-01, -1.0200e-01, -4.0800e-01]],

        [[ 1.4487e+00, -1.3027e+00, -1.1495e-01,  1.8600e-01, -1.0799e-01],
         [-2.2003e-01,  7.8611e-02,  1.1570e+00,  9.8800e-01,  2.5580e-01],
         [ 3.6400e-01,  8.0208e-01, -4.2785e-01, -1.3363e+00,  1.0139e+00],
         [ 8.7191e-01,  9.6430e-01,  5.9342e-01, -3.2455e-01,  8.9122e-01],
         [ 1.1741e+00, -5.1544e-02, -1.9774e-01,  1.2507e+00,  7.7006e-01]],

        [[-7.9737e-03, -4.9871e-02,  9.5006e-02, -1.2773e-03,  4.7520e-03],
         [-6.7919e-02, -7.0340e-02, -7.2117e-02, -8.1415e-02,  2.0171e-02],
         [ 9.5163e-04,  2.7933e-02, -1.2786e-01,  4.4112e-03,  5.8304e-02],
        

In [29]:
gray_named = (img_named * weights_aligned).sum('channels') #兩個張量相乘後，將 channels 軸內的子陣列加總
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [30]:
#若試圖將不同名稱的軸組合起來，系統會報錯:
#gray_named = (img_named[:3] * weights_named).sum('channels')

In [31]:
gray_plain = gray_named.rename(None) #將張量變回原本未命名的樣子
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [32]:
#3.5 張量的元素型別
double_points = torch.ones(10, 2, dtype=torch.double) #指定該張量內的數值為 64 位元的雙精度浮點數
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short) #指定該張量內的數值為 16 位元的整數

In [33]:
short_points.dtype #呼叫 short_point 的 dtype 屬性

torch.int16

In [34]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
print(double_points.dtype)
print(short_points.dtype)

torch.float64
torch.int16


In [35]:
#to 會檢查張量原本的數值類型與我們指定的是否一致，若不一致則轉換。
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
print(double_points.dtype)
print(short_points.dtype)

torch.float64
torch.int16


In [36]:
points_64 = torch.zeros(5, dtype=torch.double) #建立內含 5 個元素的 64 位元浮點數張量，其中元素值皆為 0
points_short = points_64.to(torch.short) #設定 points_short 為 16 位元的整數張量
points_64 * points_short #輸出結果為 64 位元的浮點數

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [37]:
#3.6 其他常用的張量功能
a = torch.ones(3, 2) # 創建一個 shape 為 3x2 的 2 軸張量
a_t = torch.transpose(a, 0, 1) #將 a 張量的第 0 軸與第 1 軸轉置
a.shape, a_t.shape #印出 a 張量及 a_t 張量的 shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [38]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)#將 a 張量的第 0 軸與第 1 軸轉置，但此處是呼叫張量的 method
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))